using System.Collections.Generic;
using XboxDownload.Helpers.Resources;

namespace XboxDownload.Models.Store;

public abstract class MarketBuilder
{
    public static IEnumerable<Market> BuildMarket() =>
    [
        new Market { Name = ResourceHelper.GetString("Store.Region.Argentina"), Code = "es-AR" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Australia"), Code = "en-AU" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Austria"), Code = "de-AT" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Belgium"), Code = "nl-BE" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Brazil"), Code = "pt-BR" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Canada"), Code = "en-CA" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Chile"), Code = "es-CL" },
        new Market { Name = ResourceHelper.GetString("Store.Region.China"), Code = "zh-CN" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Colombia"), Code = "es-CO" },
        new Market { Name = ResourceHelper.GetString("Store.Region.CzechRepublic"), Code = "cs-CZ" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Denmark"), Code = "da-DK" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Finland"), Code = "fi-FI" },
        new Market { Name = ResourceHelper.GetString("Store.Region.France"), Code = "fr-FR" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Germany"), Code = "de-DE" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Greece"), Code = "el-GR" },
        new Market { Name = ResourceHelper.GetString("Store.Region.HongKongSar"), Code = "zh-HK" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Hungary"), Code = "hu-HU" },
        new Market { Name = ResourceHelper.GetString("Store.Region.India"), Code = "en-IN" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Ireland"), Code = "en-IE" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Israel"), Code = "he-IL" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Italy"), Code = "it-IT" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Japan"), Code = "ja-JP" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Korea"), Code = "ko-KR" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Mexico"), Code = "es-MX" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Netherlands"), Code = "nl-NL" },
        new Market { Name = ResourceHelper.GetString("Store.Region.NewZealand"), Code = "en-NZ" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Norway"), Code = "nb-NO" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Poland"), Code = "pl-PL" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Portugal"), Code = "pt-PT" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Russia"), Code = "ru-RU" },
        new Market { Name = ResourceHelper.GetString("Store.Region.SaudiArabia"), Code = "ar-SA" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Singapore"), Code = "en-SG" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Slovakia"), Code = "sk-SK" },
        new Market { Name = ResourceHelper.GetString("Store.Region.SouthAfrica"), Code = "en-ZA" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Spain"), Code = "es-ES" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Sweden"), Code = "sv-SE" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Switzerland"), Code = "de-CH" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Taiwan"), Code = "zh-TW" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Turkey"), Code = "tr-TR" },
        new Market { Name = ResourceHelper.GetString("Store.Region.UnitedArabEmirates"), Code = "ar-AE" },
        new Market { Name = ResourceHelper.GetString("Store.Region.UnitedKingdom"), Code = "en-GB" },
        new Market { Name = ResourceHelper.GetString("Store.Region.UnitedStates"), Code = "en-US" }
    ];

    public static IEnumerable<Market> BuildMarket2() =>
    [
        new Market { Name = ResourceHelper.GetString("Store.Region.Algeria"), Code = "ar-DZ" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Bahrain"), Code = "ar-BH" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Bangladesh"), Code = "en-BD" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Bulgaria"), Code = "bg-BG" },
        new Market { Name = ResourceHelper.GetString("Store.Region.CostaRica"), Code = "es-CR" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Egypt"), Code = "ar-EG" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Guatemala"), Code = "es-GT" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Iceland"), Code = "is-IS" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Indonesia"), Code = "id-ID" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Iraq"), Code = "ar-IQ" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Jordan"), Code = "ar-JO" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Kazakhstan"), Code = "ru-KZ" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Kenya"), Code = "en-KE" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Kuwait"), Code = "ar-KW" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Liechtenstein"), Code = "de-LI" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Malaysia"), Code = "en-MY" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Mauritania"), Code = "ar-MR" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Nigeria"), Code = "en-NG" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Oman"), Code = "ar-OM" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Pakistan"), Code = "en-PK" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Peru"), Code = "es-PE" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Philippines"), Code = "en-PH" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Qatar"), Code = "en-QA" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Romania"), Code = "ro-RO" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Serbia"), Code = "en-RS" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Thailand"), Code = "th-TH" },
        new Market { Name = ResourceHelper.GetString("Store.Region.TrinidadAndTobago"), Code = "en-TT" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Tunisia"), Code = "ar-TN" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Ukraine"), Code = "uk-UA" },
        new Market { Name = ResourceHelper.GetString("Store.Region.Vietnam"), Code = "vi-VN" },
    ];
}