//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XboxDownload.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XboxDownload.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ###################### Microsoft ######################
        ///catalog.gamepass.com	#XGP游戏库
        ///download.xbox.com		#Xbox360主机下载域名
        ///
        ///
        ///###################### Nintendo ######################
        ///*.hac.lp1.d4c.nintendo.net
        ///*.hac.lp1.eshop.nintendo.net
        ///*.hac.lp1.dragons.nintendo.net
        ///
        ///
        ///######################### EA #########################
        ///pl.ea.com
        ///pc.ea.com
        ///www.ea.com
        ///pc-assets.ea.com
        ///ratt.juno.ea.com
        ///autopatch.juno.ea.com
        ///desktop-config.juno.ea.com
        ///split-evaluator.juno.ea.com
        ///contentful-proxy.juno.ea.com
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Akamai {
            get {
                return ResourceManager.GetString("Akamai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *akadns.net
        ///*akam.net
        ///*akamai.com
        ///*akamai.net
        ///*akamaiedge.net
        ///*akamaihd.net
        ///*akamaistream.net
        ///*akamaitech.net
        ///*akamaitechnologies.com
        ///*akamaitechnologies.fr
        ///*akamaized.net
        ///*edgekey.net
        ///*edgesuite.net
        ///*srip.net
        ///*footprint.net
        ///*level3.net
        ///*llnwd.net
        ///*edgecastcdn.net
        ///*cloudfront.net
        ///*netflix.com
        ///*netflix.net
        ///*nflximg.com
        ///*nflximg.net
        ///*nflxvideo.net
        ///*nflxso.net
        ///*nflxext.com
        ///*hulu.com
        ///*huluim.com
        ///*hbonow.com
        ///*hbogo.com
        ///*hbo.com
        ///*amazon.com
        ///*amazon.co.uk
        ///*amazonvideo.com
        ///*crackle [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SniProxy {
            get {
                return ResourceManager.GetString("SniProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Task version=&quot;1.2&quot; xmlns=&quot;http://schemas.microsoft.com/windows/2004/02/mit/task&quot;&gt;
        ///  &lt;RegistrationInfo&gt;
        ///    &lt;Description&gt;开机启动监听 + 最小化到系统托盘&lt;/Description&gt;
        ///  &lt;/RegistrationInfo&gt;
        ///  &lt;Triggers&gt;
        ///    &lt;LogonTrigger&gt;
        ///      &lt;StartBoundary&gt;2022-01-01T00:00:00&lt;/StartBoundary&gt;
        ///      &lt;Enabled&gt;true&lt;/Enabled&gt;
        ///      &lt;Delay&gt;PT30S&lt;/Delay&gt;
        ///    &lt;/LogonTrigger&gt;
        ///  &lt;/Triggers&gt;
        ///  &lt;Principals&gt;
        ///    &lt;Principal id=&quot;Author&quot;&gt;
        ///      &lt;LogonType&gt;InteractiveToken&lt;/LogonType&gt;
        ///      &lt;RunLev [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] version {
            get {
                object obj = ResourceManager.GetObject("version", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Xbox {
            get {
                object obj = ResourceManager.GetObject("Xbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Xbox1 {
            get {
                object obj = ResourceManager.GetObject("Xbox1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Xbox2 {
            get {
                object obj = ResourceManager.GetObject("Xbox2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Xbox3 {
            get {
                object obj = ResourceManager.GetObject("Xbox3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] XboxDownload {
            get {
                object obj = ResourceManager.GetObject("XboxDownload", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Xbox下载助手 {
            get {
                object obj = ResourceManager.GetObject("Xbox下载助手", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
