<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <Version>1.1.1</Version>
        <FileVersion>1.1.1</FileVersion>
        <AssemblyTitle>XboxFastz</AssemblyTitle>
        <Product>XboxFastz</Product>
        <Description>XboxFastZ</Description>
        <ApplicationIcon>Assets\xbox.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <AvaloniaResource Include="Resources\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="DnsClient" Version="1.8.0" />
        <PackageReference Include="DynamicData" Version="9.4.33" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
        <PackageReference Include="System.Management" Version="10.0.10" />
        <PackageReference Include="WindowsFirewallHelper" Version="2.2.0.86" />
    </ItemGroup>
</Project>
